#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TextAnalysis;

namespace TextAnalysis	
{
	public partial class DudenCacheModel : OpenAccessContext, IDudenCacheModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("DudenCacheModel.rlinq");
		
		public DudenCacheModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public DudenCacheModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public DudenCacheModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public DudenCacheModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public DudenCacheModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<WordDefinition> WordDefinitions 
		{
			get
			{
				return this.GetAll<WordDefinition>();
			}
		}
		
		public IQueryable<WordMatch> WordMatches 
		{
			get
			{
				return this.GetAll<WordMatch>();
			}
		}
		
		public IQueryable<SynonymMatch> SynonymMatches 
		{
			get
			{
				return this.GetAll<SynonymMatch>();
			}
		}
		
		public IQueryable<WordTyp> WordTyps 
		{
			get
			{
				return this.GetAll<WordTyp>();
			}
		}
		
		public IQueryable<WordFrequency> WordFrequencies 
		{
			get
			{
				return this.GetAll<WordFrequency>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of DudenCacheModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of DudenCacheModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IDudenCacheModelUnitOfWork : IUnitOfWork
	{
		IQueryable<WordDefinition> WordDefinitions
		{
			get;
		}
		IQueryable<WordMatch> WordMatches
		{
			get;
		}
		IQueryable<SynonymMatch> SynonymMatches
		{
			get;
		}
		IQueryable<WordTyp> WordTyps
		{
			get;
		}
		IQueryable<WordFrequency> WordFrequencies
		{
			get;
		}
	}
}
#pragma warning restore 1591
