#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using TextAnalysis;

namespace TextAnalysis	
{
	[System.Serializable()]
	public partial class SynonymMatch : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _baseDefinitionId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string BaseDefinitionId
		{
			get
			{
				return this._baseDefinitionId;
			}
			set
			{
				if(this._baseDefinitionId != value)
				{
					this.OnPropertyChanging("BaseDefinitionId");
					this._baseDefinitionId = value;
					this.OnPropertyChanged("BaseDefinitionId");
				}
			}
		}
		
		private string _synonymId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string SynonymId
		{
			get
			{
				return this._synonymId;
			}
			set
			{
				if(this._synonymId != value)
				{
					this.OnPropertyChanging("SynonymId");
					this._synonymId = value;
					this.OnPropertyChanged("SynonymId");
				}
			}
		}
		
		private WordDefinition _wordDefinition1;
		public virtual WordDefinition Synonym
		{
			get
			{
				return this._wordDefinition1;
			}
			set
			{
				if(this._wordDefinition1 != value)
				{
					this.OnPropertyChanging("Synonym");
					this._wordDefinition1 = value;
					this.OnPropertyChanged("Synonym");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public SynonymMatch()
		{
		}
		
		protected SynonymMatch(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.BaseDefinitionId = info.GetString("BaseDefinitionId");
			this.SynonymId = info.GetString("SynonymId");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("BaseDefinitionId", this.BaseDefinitionId, typeof(string));
			info.AddValue("SynonymId", this.SynonymId, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
